// Campaign Finance Data
const rawData = [
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "John Franklin",
        "committee_name": "John Franklin for Supervisor 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$231,366.00",
        "loans_received": "$0.00",
        "total_contributions": "$231,366.00",
        "total_expenditures": "$95,690.43",
        "cash_on_hand": "$615,569.28",
        "outstanding_debt": "$30,115.70",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "John Franklin",
        "committee_name": "John Franklin for Supervisor 2026",
        "period_start": "7/1/24",
        "period_end": "12/31/24",
        "date_filed": "1/31/25",
        "monetary_contributions": "$25,699.00",
        "loans_received": "$0.00",
        "total_contributions": "$25,699.00",
        "total_expenditures": "$9,869.26",
        "cash_on_hand": "$449,531.26",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "John Franklin",
        "committee_name": "John Franklin for Supervisor 2026",
        "period_start": "2/18/24",
        "period_end": "6/30/24",
        "date_filed": "7/31/24",
        "monetary_contributions": "$46,502.00",
        "loans_received": "$0.00",
        "total_contributions": "$46,502.00",
        "total_expenditures": "$4,791.08",
        "cash_on_hand": "$435,588.76",
        "outstanding_debt": "$1,887.24",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "John Franklin",
        "committee_name": "John Franklin for Supervisor 2026",
        "period_start": "1/21/24",
        "period_end": "2/27/24",
        "date_filed": "2/20/24",
        "monetary_contributions": "$3,099.00",
        "loans_received": "$0.00",
        "total_contributions": "$3,099.00",
        "total_expenditures": "$2,038.21",
        "cash_on_hand": "$391,990.60",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "John Franklin",
        "committee_name": "John Franklin for Supervisor 2026",
        "period_start": "1/1/24",
        "period_end": "1/20/24",
        "date_filed": "1/24/24",
        "monetary_contributions": "$4,314.00",
        "loans_received": "$0.00",
        "total_contributions": "$4,314.00",
        "total_expenditures": "$777.00",
        "cash_on_hand": "$390,929.81",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "John Franklin",
        "committee_name": "John Franklin for Supervisor 2026",
        "period_start": "1/1/23",
        "period_end": "12/31/23",
        "date_filed": "1/5/24",
        "monetary_contributions": "$405,907.99",
        "loans_received": "$55.00",
        "total_contributions": "$406,407.99",
        "total_expenditures": "$19,015.18",
        "cash_on_hand": "$387,392.81",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "Rebecca Jones",
        "committee_name": "Jones for Supervisor 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$97,358.80",
        "loans_received": "$0.00",
        "total_contributions": "$99,465.71",
        "total_expenditures": "$36,068.40",
        "cash_on_hand": "$148,428.50",
        "outstanding_debt": "$1,700.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "Rebecca Jones",
        "committee_name": "Jones for Supervisor 2026",
        "period_start": "7/1/24",
        "period_end": "12/31/24",
        "date_filed": "1/31/25",
        "monetary_contributions": "$6,615.24",
        "loans_received": "$0.00",
        "total_contributions": "$6,615.24",
        "total_expenditures": "$11,044.48",
        "cash_on_hand": "$83,331.19",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "Rebecca Jones",
        "committee_name": "Jones for Supervisor 2026",
        "period_start": "1/1/24",
        "period_end": "6/30/24",
        "date_filed": "7/31/24",
        "monetary_contributions": "$119,112.45",
        "loans_received": "$0.00",
        "total_contributions": "$119,112.45",
        "total_expenditures": "$31,352.03",
        "cash_on_hand": "$95,269.60",
        "outstanding_debt": "$7,509.17",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/228",
        "office": "Supervisor",
        "district": "5",
        "candidate_name": "Kyle Krahel",
        "committee_name": "Kyle Krahel for San Diego County Supervisor 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/227",
        "office": "Supervisor",
        "district": "4",
        "candidate_name": "Monica Montgomery Steppe",
        "committee_name": "Re-Elect Montgomery Steppe for Supervisor 2026",
        "period_start": "7/1/24",
        "period_end": "21/31/2024",
        "date_filed": "1/30/25",
        "monetary_contributions": "$13,502.26",
        "loans_received": "$0.00",
        "total_contributions": "$13,502.26",
        "total_expenditures": "$3,320.00",
        "cash_on_hand": "$10,182.26",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/227",
        "office": "Supervisor",
        "district": "4",
        "candidate_name": "Monica Montgomery Steppe",
        "committee_name": "Re-Elect Montgomery Steppe for Supervisor 2026",
        "period_start": "1/1/24",
        "period_end": "6/30/24",
        "date_filed": "7/31/24",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$0.00",
        "cash_on_hand": "$0.00",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/227",
        "office": "Supervisor",
        "district": "4",
        "candidate_name": "Monica Montgomery Steppe",
        "committee_name": "Re-Elect Montgomery Steppe for Supervisor 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$1,916.07",
        "cash_on_hand": "$8,887.26",
        "outstanding_debt": "$621.07",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/9",
        "office": "Assessor",
        "district": "",
        "candidate_name": "Jordan Marks",
        "committee_name": "Marks for Assessor 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "8/12/25",
        "monetary_contributions": "$670,016.00",
        "loans_received": "$9.00",
        "total_contributions": "$670,016.00",
        "total_expenditures": "$73,787.77",
        "cash_on_hand": "$641,569.03",
        "outstanding_debt": "$42,000.00",
        "amended": "1",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1618",
        "office": "City Council",
        "district": "2",
        "candidate_name": "John Coyne",
        "committee_name": "Josh Coyne for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$69,148.00",
        "loans_received": "$30,000.00",
        "total_contributions": "$99,148.00",
        "total_expenditures": "$17,151.55",
        "cash_on_hand": "$91,261.25",
        "outstanding_debt": "$39,264.80",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/99749be3-1279-49df-8baa-40aafddcba91"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1618",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Mandy Havlik",
        "committee_name": "Havlik for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/30/25",
        "monetary_contributions": "$22,058.00",
        "loans_received": "$20,000.00",
        "total_contributions": "$42,058.00",
        "total_expenditures": "$15,726.62",
        "cash_on_hand": "$26,842.33",
        "outstanding_debt": "$20,510.95",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/8c299a61-27b2-4d4b-be09-9516f979d919"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1618",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Nicole Crosby",
        "committee_name": "Nicole Crosby for San Diego City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/29/25",
        "monetary_contributions": "$21,834.00",
        "loans_received": "$0.00",
        "total_contributions": "$21,834.00",
        "total_expenditures": "$6,811.53",
        "cash_on_hand": "$15,135.67",
        "outstanding_debt": "$113.20",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/b74440a2-fc97-43db-9099-56554958a277"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1620",
        "office": "City Council",
        "district": "4",
        "candidate_name": "Martha Abraham",
        "committee_name": "Martha Abraham for City Council 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1620",
        "office": "City Council",
        "district": "4",
        "candidate_name": "Roosevelt Williams III",
        "committee_name": "Friends of Roosevelt Williams III for City Council 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1620",
        "office": "City Council",
        "district": "4",
        "candidate_name": "Henry Foster",
        "committee_name": "Re-Elect Henry Foster III for San Diego City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$6,050.00",
        "loans_received": "$0.00",
        "total_contributions": "$6,050.00",
        "total_expenditures": "$819.23",
        "cash_on_hand": "$5,780.77",
        "outstanding_debt": "$550.00",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/23a7f6d2-2411-4cff-828c-19ec183067d2"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1622",
        "office": "City Council",
        "district": "6",
        "candidate_name": "Kent Lee",
        "committee_name": "\tRe-Elect Kent Lee for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$1,629.00",
        "loans_received": "$0.00",
        "total_contributions": "$1,629.00",
        "total_expenditures": "$627.81",
        "cash_on_hand": "$1,551.19",
        "outstanding_debt": "$550.00",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/d2eb5f81-ea42-4e93-991f-18d7a5467f8a"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1624",
        "office": "City Council",
        "district": "8",
        "candidate_name": "Rafael A. Perez",
        "committee_name": "Perez for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$19,080.00",
        "loans_received": "$0.00",
        "total_contributions": "$19,206.31",
        "total_expenditures": "$5,093.91",
        "cash_on_hand": "$15,856.17",
        "outstanding_debt": "$1,743.77",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/65da7550-7c17-408a-b288-3bb3a9a787c1"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1624",
        "office": "City Council",
        "district": "8",
        "candidate_name": "Venus Molina",
        "committee_name": "Venus Molina for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$66,234.11",
        "loans_received": "$0.00",
        "total_contributions": "$66,234.11",
        "total_expenditures": "$15,400.71",
        "cash_on_hand": "$57,508.49",
        "outstanding_debt": "$6,675.03",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/f149159b-c563-454a-a08c-74edab98c983"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1624",
        "office": "City Council",
        "district": "8",
        "candidate_name": "Francisco A. Mayoral Munoz",
        "committee_name": "Mayoral Munoz for City Council 2026\t",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1624",
        "office": "City Council",
        "district": "8",
        "candidate_name": "Antonio Martinez",
        "committee_name": "Antonio Antonio Martinez for City Council 2026\t",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "8/1/25",
        "monetary_contributions": "$49,688.00",
        "loans_received": "$0.00",
        "total_contributions": "$50,552.25",
        "total_expenditures": "$13,889.54",
        "cash_on_hand": "$81,570.05",
        "outstanding_debt": "$11,093.50",
        "amended": "",
        "link": "https://efile.sandiego.gov/public/direct/942e58f9-9283-4fc1-88eb-c1925250caf5"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1626",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Joy Emmanuel",
        "committee_name": "Joy Emmanuel for Chula Vista City Council District 1, 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/18/25",
        "monetary_contributions": "$1,350.00",
        "loans_received": "$0.00",
        "total_contributions": "$1,350.00",
        "total_expenditures": "$44.17",
        "cash_on_hand": "$1,305.83",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=UytFeUJ0cHdWeVoyUUM5MzY3T2hwdz09&aid=CCV"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/610",
        "office": "Mayor",
        "district": "",
        "candidate_name": "John McCann",
        "committee_name": "McCann for Mayor 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1626",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Melanie Burkholder",
        "committee_name": "Burkholder for City Council 2026",
        "period_start": "1/1/23",
        "period_end": "6/30/23",
        "date_filed": "7/25/23",
        "monetary_contributions": "$150.00",
        "loans_received": "$0.00",
        "total_contributions": "$150.00",
        "total_expenditures": "$66.98",
        "cash_on_hand": "$83.02",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=Zk15UlpSTGxpM2FDQytKbHMwTDJtZz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1626",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Melanie Burkholder",
        "committee_name": "Burkholder for City Council 2026",
        "period_start": "7/1/23",
        "period_end": "12/31/23",
        "date_filed": "1/31/24",
        "monetary_contributions": "$1,890.63",
        "loans_received": "$0.00",
        "total_contributions": "$1,890.63",
        "total_expenditures": "$1,254.97",
        "cash_on_hand": "$718.68",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=SEtrM3pjcWkvTXczUkRNOWc1UGJNZz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1626",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Melanie Burkholder",
        "committee_name": "Burkholder for City Council 2026",
        "period_start": "1/1/24",
        "period_end": "6/30/24",
        "date_filed": "7/28/204",
        "monetary_contributions": "$126.03",
        "loans_received": "$0.00",
        "total_contributions": "$126.03",
        "total_expenditures": "$394.97",
        "cash_on_hand": "$449.74",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=Y3ZhUkVLM0lIQTFpaThTK00yRHNHdz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1626",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Melanie Burkholder",
        "committee_name": "Burkholder for City Council 2026",
        "period_start": "7/1/24",
        "period_end": "12/31/24",
        "date_filed": "1/31/25",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$90.00",
        "cash_on_hand": "$359.74",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=ZktSR1B6MnE0U1k3TENEMmM1TnJCZz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1626",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Melanie Burkholder",
        "committee_name": "Burkholder for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/28/25",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$340.00",
        "cash_on_hand": "$269.74",
        "outstanding_debt": "$250.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=ZmNyb2VTZHVMeUZjME9Bc1BBT0VBdz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1615",
        "office": "City Council",
        "district": "3",
        "candidate_name": "Priya Bhat-Patel",
        "committee_name": "Re-Elect Priya Bhat-Patel for City Council 2026",
        "period_start": "1/1/23",
        "period_end": "6/30/23",
        "date_filed": "7/29/23",
        "monetary_contributions": "$11,705.59",
        "loans_received": "$0.00",
        "total_contributions": "$11,705.59",
        "total_expenditures": "$5,146.81",
        "cash_on_hand": "$7,493.78",
        "outstanding_debt": "$935.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=a001Y21CcW93dTByc1NKMFFSYXkvUT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1615",
        "office": "City Council",
        "district": "3",
        "candidate_name": "Priya Bhat-Patel",
        "committee_name": "Re-Elect Priya Bhat-Patel for City Council 2026",
        "period_start": "7/1/23",
        "period_end": "12/31/23",
        "date_filed": "1/30/24",
        "monetary_contributions": "$107.00",
        "loans_received": "$0.00",
        "total_contributions": "$107.00",
        "total_expenditures": "$4,715.81",
        "cash_on_hand": "$2,934.97",
        "outstanding_debt": "$935.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=bXdFWGlCWTdscDgwczZFNVVSWVdVZz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1615",
        "office": "City Council",
        "district": "3",
        "candidate_name": "Priya Bhat-Patel",
        "committee_name": "Re-Elect Priya Bhat-Patel for City Council 2026",
        "period_start": "1/1/24",
        "period_end": "6/30/24",
        "date_filed": "7/31/24",
        "monetary_contributions": "$2,732.00",
        "loans_received": "$0.00",
        "total_contributions": "$2,732.00",
        "total_expenditures": "$3,327.85",
        "cash_on_hand": "$2,349.12",
        "outstanding_debt": "$975.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=dDkzZ1hPcEZaRlBWcFRGaUtkOU45UT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1615",
        "office": "City Council",
        "district": "3",
        "candidate_name": "Priya Bhat-Patel",
        "committee_name": "Re-Elect Priya Bhat-Patel for City Council 2026",
        "period_start": "7/1/24",
        "period_end": "12/31/24",
        "date_filed": "1/28/25",
        "monetary_contributions": "$3,155.00",
        "loans_received": "$0.00",
        "total_contributions": "$3,155.00",
        "total_expenditures": "$3,209.08",
        "cash_on_hand": "$1,990.04",
        "outstanding_debt": "$670.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=SUhyemIySHFPUUVYQTlKSXY3Ti9CQT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1615",
        "office": "City Council",
        "district": "3",
        "candidate_name": "Priya Bhat-Patel",
        "committee_name": "Re-Elect Priya Bhat-Patel for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/28/25",
        "monetary_contributions": "$3,532.00",
        "loans_received": "$0.00",
        "total_contributions": "$3,532.00",
        "total_expenditures": "$2,466.19",
        "cash_on_hand": "$3,987.45",
        "outstanding_debt": "$1,601.60",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=OWduSGlOZXZ6UkVlOEJISFpzVVdsUT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/599",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Keith Blackburn",
        "committee_name": "Keith Blackburn for Mayor 2026",
        "period_start": "7/1/23",
        "period_end": "12/31/23",
        "date_filed": "1/31/24",
        "monetary_contributions": "$450.00",
        "loans_received": "$0.00",
        "total_contributions": "$450.00",
        "total_expenditures": "$2,502.85",
        "cash_on_hand": "$67,400.27",
        "outstanding_debt": "$13,178.12",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=ZUllalp3ZjBxRjJEMksvUldnMjR5QT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/599",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Keith Blackburn",
        "committee_name": "Keith Blackburn for Mayor 2026",
        "period_start": "1/1/24",
        "period_end": "6/30/24",
        "date_filed": "7/31/24",
        "monetary_contributions": "$57,999.00",
        "loans_received": "$0.00",
        "total_contributions": "$57,999.00",
        "total_expenditures": "$2,105.64",
        "cash_on_hand": "$123,328.63",
        "outstanding_debt": "$13,178.12",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=NEV5VEh2Sm5qbkowU3JOVU9adHpkQT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/599",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Keith Blackburn",
        "committee_name": "Keith Blackburn for Mayor 2026",
        "period_start": "1/1/23",
        "period_end": "6/30/23",
        "date_filed": "7/24/23",
        "monetary_contributions": "$56,275.00",
        "loans_received": "$13,178.12",
        "total_contributions": "$69,453.12",
        "total_expenditures": "$0.00",
        "cash_on_hand": "$69,453.12",
        "outstanding_debt": "$13,178.12",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=ZUllalp3ZjBxRjJEMksvUldnMjR5QT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/599",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Keith Blackburn",
        "committee_name": "Keith Blackburn for Mayor 2026",
        "period_start": "7/1/24",
        "period_end": "12/31/24",
        "date_filed": "1/31/25",
        "monetary_contributions": "$26,950.00",
        "loans_received": "$0.00",
        "total_contributions": "$26,950.00",
        "total_expenditures": "$608.19",
        "cash_on_hand": "$149,670.44",
        "outstanding_debt": "$13,178.12",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=Y2s5dUREVjBYRXJBSEkvMmwwbmNqUT09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/599",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Keith Blackburn",
        "committee_name": "Keith Blackburn for Mayor 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$11,300.00",
        "loans_received": "$0.00",
        "total_contributions": "$11,300.00",
        "total_expenditures": "$643.97",
        "cash_on_hand": "$160,326.47",
        "outstanding_debt": "$13,178.12",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=cVowN2JTenl2SXV5RGNRM052cnVWdz09&aid=CAR"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/599",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Dane White",
        "committee_name": "Dane White for Mayor 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$3,800.00",
        "loans_received": "$0.00",
        "total_contributions": "$3,800.00",
        "total_expenditures": "$1,331.09",
        "cash_on_hand": "$3,529.41",
        "outstanding_debt": "$1,060.50",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=dFRWSDZJVGw4SlBxVEUva0FsUGkyUT09&aid=ESC"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1639",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Joe Garcia",
        "committee_name": "Joe Garcia for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/12/25",
        "monetary_contributions": "$3,800.00",
        "loans_received": "$0.00",
        "total_contributions": "$3,800.00",
        "total_expenditures": "$3,348.09",
        "cash_on_hand": "$451.91",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=TWtxQytHZ2kxN09XYm52RnYvVzM2dz09&aid=ESC"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/740",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Patricia Dillard",
        "committee_name": "Patricia Dillard for La Mesa Mayor 2026\t",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$2,548.00",
        "loans_received": "$0.00",
        "total_contributions": "$2,548.00",
        "total_expenditures": "$624.85",
        "cash_on_hand": "$2,473.15",
        "outstanding_debt": "$550.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=dS91bGRrS1BvSkdNTXVVZHhPaWw3Zz09&aid=LMSA"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/740",
        "office": "City Council",
        "district": "",
        "candidate_name": "Moana Alo",
        "committee_name": "Moana Alo for City Council 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/816",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Jose Rodriguez",
        "committee_name": "Jose Rodriguez for Mayor 2026\t",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1650",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Eric Joyce",
        "committee_name": "Joyce for City Council 2026",
        "period_start": "1/1/23",
        "period_end": "6/30/23",
        "date_filed": "7/28/23",
        "monetary_contributions": "$8,083.30",
        "loans_received": "$0.00",
        "total_contributions": "$8,083.30",
        "total_expenditures": "$593.84",
        "cash_on_hand": "$7,489.48",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=cSsxcGhoWTNBcWhjU3lGOTRZeXA2dz09&aid=OCN"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1650",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Eric Joyce",
        "committee_name": "Joyce for City Council 2026",
        "period_start": "7/1/23",
        "period_end": "12/31/23",
        "date_filed": "1/20/24",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$2,564.02",
        "cash_on_hand": "$4,925.46",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=U0xuSmFtL3VDME9RbXdIZEM2OTdDdz09&aid=OCN"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1650",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Eric Joyce",
        "committee_name": "Joyce for City Council 2026",
        "period_start": "1/1/24",
        "period_end": "2/17/24",
        "date_filed": "2/23/24",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$518.53",
        "cash_on_hand": "$4,406.93",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=UU0wYlUwcHFUVnpsZUVacHZNVkMwdz09&aid=OCN"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1650",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Eric Joyce",
        "committee_name": "Joyce for City Council 2026",
        "period_start": "2/18/24",
        "period_end": "6/30/24",
        "date_filed": "7/19/24",
        "monetary_contributions": "$170.00",
        "loans_received": "$0.00",
        "total_contributions": "$170.00",
        "total_expenditures": "$2,438.07",
        "cash_on_hand": "$2,138.86",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=OG9TMFVnbnpOUEtiVWRqTUxDNXdxdz09&aid=OCN"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1650",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Eric Joyce",
        "committee_name": "Joyce for City Council 2026",
        "period_start": "7/1/24",
        "period_end": "12/31/24",
        "date_filed": "1/15/25",
        "monetary_contributions": "$120.00",
        "loans_received": "$0.00",
        "total_contributions": "$120.00",
        "total_expenditures": "$1,729.14",
        "cash_on_hand": "$3,029.72",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=U0YyVHFMNThTL0paODQ3TnBKcjUvdz09&aid=OCN"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1650",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Eric Joyce",
        "committee_name": "Joyce for City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/15/25",
        "monetary_contributions": "$370.00",
        "loans_received": "$0.00",
        "total_contributions": "$370.00",
        "total_expenditures": "$3,386.05",
        "cash_on_hand": "$2,613.67",
        "outstanding_debt": "$250.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=dTVVWjZlQzFGSVV6ejFKRUNkTzU3dz09&aid=OCN"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1651",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Rick Robinson",
        "committee_name": "Re Elect Rick Robinson City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$12,368.37",
        "loans_received": "$4,000.00",
        "total_contributions": "$16,368.37",
        "total_expenditures": "$2,517.63",
        "cash_on_hand": "$13,850.74",
        "outstanding_debt": "$4,000.00",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/914",
        "office": "Mayor",
        "district": "",
        "candidate_name": "Sharon Jenkins",
        "committee_name": "Sharon Jenkins for Mayor 2026\t",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1659",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Lindsey Smith",
        "committee_name": "Smith for City Council 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1659",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Alison Stanton",
        "committee_name": "Alison Stanton for San Marcos City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$0.00",
        "loans_received": "$0.00",
        "total_contributions": "$0.00",
        "total_expenditures": "$0.00",
        "cash_on_hand": "$0.00",
        "outstanding_debt": "$0.00",
        "amended": "",
        "link": "https://public.netfile.com/pub2/RequestPDF.aspx?id=SnJIcFdTR28vYW5Wd1Jva1VvSmVodz09&aid=MRCS"
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1659",
        "office": "City Council",
        "district": "2",
        "candidate_name": "Justin Matsushita",
        "committee_name": "\tMatsushita for City Council 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1670",
        "office": "City Council",
        "district": "1",
        "candidate_name": "Frank Nunez",
        "committee_name": "Nunez for Vista City Council Dist 1 2026",
        "period_start": "",
        "period_end": "",
        "date_filed": "",
        "monetary_contributions": "",
        "loans_received": "",
        "total_contributions": "",
        "total_expenditures": "",
        "cash_on_hand": "",
        "outstanding_debt": "",
        "amended": "",
        "link": ""
    },
    {
        "jurisdiction": "https://theballotbook.com/jurisdictions/1673",
        "office": "City Council",
        "district": "4",
        "candidate_name": "Dan O'Donnell",
        "committee_name": "Dan O'Donnell for Vista City Council 2026",
        "period_start": "1/1/25",
        "period_end": "6/30/25",
        "date_filed": "7/31/25",
        "monetary_contributions": "$150.00",
        "loans_received": "$0.00",
        "total_contributions": "$150.00",
        "total_expenditures": "$150.00",
        "cash_on_hand": "$0.00",
        "outstanding_debt": "$150.00",
        "amended": "",
        "link": ""
    }
];

// Utility function to add UTM parameters to jurisdiction URLs
function getJurisdictionUrl(jurisdictionUrl) {
    if (!jurisdictionUrl || !jurisdictionUrl.startsWith('http')) {
        return '#';
    }
    
    const utmParams = new URLSearchParams({
        utm_source: 'sd_campaign_tracker',
        utm_medium: 'jurisdiction_link',
        utm_campaign: 'county_tracker'
    });
    
    const separator = jurisdictionUrl.includes('?') ? '&' : '?';
    return `${jurisdictionUrl}${separator}${utmParams.toString()}`;
}

// Utility function to parse currency strings
function parseCurrency(str) {
    if (!str || str === '') return 0;
    return parseFloat(str.replace(/[\$,]/g, ''));
}

// Utility function to format currency
function formatCurrency(num) {
    if (num === 0) return '$0';
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
    }).format(num);
}

// Process data to aggregate by candidate
function processData() {
    const candidateMap = new Map();
    
    rawData.forEach(record => {
        const key = `${record.candidate_name}_${record.jurisdiction}_${record.office}_${record.district}`;
        
        if (!candidateMap.has(key)) {
            candidateMap.set(key, {
                candidate_name: record.candidate_name,
                committee_name: record.committee_name,
                jurisdiction: record.jurisdiction,
                office: record.office,
                district: record.district,
                total_monetary_contributions: 0,
                total_loans_received: 0,
                total_contributions_sum: 0,
                total_expenditures_sum: 0,
                cash_on_hand: 0,
                outstanding_debt: 0,
                reports_filed: 0,
                latest_date_filed: '',
                link: record.link || '',
                reports: []
            });
        }
        
        const candidate = candidateMap.get(key);
        
        // Only process records with data
        if (record.monetary_contributions && record.monetary_contributions !== '') {
            candidate.total_monetary_contributions += parseCurrency(record.monetary_contributions);
            candidate.total_loans_received += parseCurrency(record.loans_received);
            candidate.total_contributions_sum += parseCurrency(record.total_contributions);
            candidate.total_expenditures_sum += parseCurrency(record.total_expenditures);
            candidate.reports_filed++;
            
            // Use the most recent cash on hand and outstanding debt
            const currentDate = new Date(record.date_filed);
            const latestDate = candidate.latest_date_filed ? new Date(candidate.latest_date_filed) : new Date('1970-01-01');
            
            if (currentDate >= latestDate) {
                candidate.cash_on_hand = parseCurrency(record.cash_on_hand);
                candidate.outstanding_debt = parseCurrency(record.outstanding_debt);
                candidate.latest_date_filed = record.date_filed;
                if (record.link) candidate.link = record.link;
            }
            
            candidate.reports.push({
                period: `${record.period_start} - ${record.period_end}`,
                date_filed: record.date_filed,
                monetary_contributions: parseCurrency(record.monetary_contributions),
                total_contributions: parseCurrency(record.total_contributions),
                total_expenditures: parseCurrency(record.total_expenditures),
                cash_on_hand: parseCurrency(record.cash_on_hand),
                link: record.link
            });
        }
    });
    
    return Array.from(candidateMap.values());
}

// Get unique races
function getRaces(processedData) {
    const raceSet = new Set();
    processedData.forEach(candidate => {
        const raceKey = `${candidate.jurisdiction} - ${candidate.office}${candidate.district ? ` District ${candidate.district}` : ''}`;
        raceSet.add(raceKey);
    });
    return Array.from(raceSet).sort();
}

// Filter candidates by race
function getCandidatesByRace(processedData, raceFilter) {
    if (!raceFilter || raceFilter === 'all') return processedData;
    
    return processedData.filter(candidate => {
        const candidateRace = `${candidate.jurisdiction} - ${candidate.office}${candidate.district ? ` District ${candidate.district}` : ''}`;
        return candidateRace === raceFilter;
    });
}

// Export processed data
const processedCandidates = processData();
const availableRaces = getRaces(processedCandidates);